// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package data

import (
	"template/api/data"
)

type ControllerV1 struct{}

func NewV1() data.IDataV1 {
	return &ControllerV1{}
}
