// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: grpc/templateGRPC/v1/hello.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayReq) Reset() {
	*x = SayReq{}
	mi := &file_grpc_templateGRPC_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayReq) ProtoMessage() {}

func (x *SayReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_templateGRPC_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayReq.ProtoReflect.Descriptor instead.
func (*SayReq) Descriptor() ([]byte, []int) {
	return file_grpc_templateGRPC_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SayRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayRes) Reset() {
	*x = SayRes{}
	mi := &file_grpc_templateGRPC_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRes) ProtoMessage() {}

func (x *SayRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_templateGRPC_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRes.ProtoReflect.Descriptor instead.
func (*SayRes) Descriptor() ([]byte, []int) {
	return file_grpc_templateGRPC_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SayRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_grpc_templateGRPC_v1_hello_proto protoreflect.FileDescriptor

const file_grpc_templateGRPC_v1_hello_proto_rawDesc = "" +
	"\n" +
	" grpc/templateGRPC/v1/hello.proto\x12\x0ftemplateGRPC.v1\"\"\n" +
	"\x06SayReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\"\n" +
	"\x06SayRes\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2@\n" +
	"\x05Hello\x127\n" +
	"\x03Say\x12\x17.templateGRPC.v1.SayReq\x1a\x17.templateGRPC.v1.SayResB\x1aZ\x18api/grpc/templateGRPC/v1b\x06proto3"

var (
	file_grpc_templateGRPC_v1_hello_proto_rawDescOnce sync.Once
	file_grpc_templateGRPC_v1_hello_proto_rawDescData []byte
)

func file_grpc_templateGRPC_v1_hello_proto_rawDescGZIP() []byte {
	file_grpc_templateGRPC_v1_hello_proto_rawDescOnce.Do(func() {
		file_grpc_templateGRPC_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_templateGRPC_v1_hello_proto_rawDesc), len(file_grpc_templateGRPC_v1_hello_proto_rawDesc)))
	})
	return file_grpc_templateGRPC_v1_hello_proto_rawDescData
}

var file_grpc_templateGRPC_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_templateGRPC_v1_hello_proto_goTypes = []any{
	(*SayReq)(nil), // 0: templateGRPC.v1.SayReq
	(*SayRes)(nil), // 1: templateGRPC.v1.SayRes
}
var file_grpc_templateGRPC_v1_hello_proto_depIdxs = []int32{
	0, // 0: templateGRPC.v1.Hello.Say:input_type -> templateGRPC.v1.SayReq
	1, // 1: templateGRPC.v1.Hello.Say:output_type -> templateGRPC.v1.SayRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_templateGRPC_v1_hello_proto_init() }
func file_grpc_templateGRPC_v1_hello_proto_init() {
	if File_grpc_templateGRPC_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_templateGRPC_v1_hello_proto_rawDesc), len(file_grpc_templateGRPC_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_templateGRPC_v1_hello_proto_goTypes,
		DependencyIndexes: file_grpc_templateGRPC_v1_hello_proto_depIdxs,
		MessageInfos:      file_grpc_templateGRPC_v1_hello_proto_msgTypes,
	}.Build()
	File_grpc_templateGRPC_v1_hello_proto = out.File
	file_grpc_templateGRPC_v1_hello_proto_goTypes = nil
	file_grpc_templateGRPC_v1_hello_proto_depIdxs = nil
}
