// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package predict

import (
	"template/api/predict"
)

type ControllerV1 struct{}

func NewV1() predict.IPredictV1 {
	return &ControllerV1{}
}
